import { Inter } from "next/font/google";
import "./globals.css";
import Footer from "@/app/components/footerlayout/footer";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "에어비앤비",
  description: "Generated by create next app",
  icons: {
    icon: "/public/common/smallLogo.png",
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/common/favicon.ico" />
      </head>
      <body>{children}</body>
    </html>
  );
}
